services:
    client:
        container_name: wc-auth-concept
        build: ./client
        volumes:
          - ./client/src/:/app/src
          - /app/node_modules
        ports:
          - 8080:3000
        environment:
          - CHOKIDAR_USEPOLLING=true
    server:
        build: ./server
        ports:
            - 5050:5000
        command: npm run dev
        volumes:
            - ./server/src/:/app/src/
    mongodb:
        image: mongo
        volumes:
            - ./data:/data/db